### ISSUE TITLE
Documentation suggestion for Arduino 2.2.1

### ISSUE THREAD

**Issue by grymoire** [cecio/USBvalve#10]
Using Arduino 2.2.1, after selecting board and CPU speed, you must set  Tools=>USB Stack to "Adafruit TinyUSB"

**Comment by cecio** [comment]
Good point, I'll add this.
Thanks!

**Comment by cecio** [comment]
I'm going to release a new version over the weekend, I'll do this update as well.

**Comment by cecio** [comment]
Done. Thanks for your suggestion.
