### ISSUE TITLE
STL-files for the narrow LCD?

### ISSUE THREAD

**Issue by n00btotal** [cecio/USBvalve#11]
From what I can tell from the STL-files. The box is for the "narrow" (32) LCD-display. 

Any plans of releasing a version of the STL-files for the broad-version (64)?

(If not, I guess I have to learn to CAD and do it myself and add it here.. But that will take some time I guess.)

**Comment by cecio** [comment]
Hey.

Yes, you are right, right know the STL Cover is only for the 32 LCD. 
I think I can work on it to create a 64 version, but I ran out of 64 samples, so I have to build one.

I think I can work on it, it will not be super-fast, but if you have some patience :-)

**Comment by cecio** [comment]
see Issue #36
