### ISSUE TITLE
Add support for M5Stack StickC Plus2

### ISSUE THREAD

**Issue by Awlexegrecki** [cecio/USBvalve#13]
Would it be possible to add this hardware to an M5Stac StickC Plus2? I think that this would be one of the best devices for this software.

**Comment by cecio** [comment]
Hey, thanks for reaching out. 
I didn't know about this board, very interesting.
For sure I think it is technically possible to port USBvalve to this board, even if it will require some work: the MCU on which it is based it's a different one, so it will probably require some work (not huge, but still some work).
Right now I don't have plan to do it, but if anyone out there want to contribute, I'm more than happy to consider pull requests :-)
