### ISSUE TITLE
Passthrough Charging Without Data Connection?

### ISSUE THREAD

**Issue by anseltaft** [cecio/USBvalve#15]
Is it possible to have a version of this that stays connected to monitor what's going on with the data connection of the USB charger, but passes the rest of the charge on to a device plugged into the other end of the USBValve?

**Comment by cecio** [comment]
Hey, thanks for your interest in the project.

I'm not sure I fully got your question, but right now, power is passed through the Host USB port (PCB version 1.2). 
What is not happening is that data are not passed through the ports, so the two ports are independent.
Let me know if this not answer your question.
Thanks,
