### ISSUE TITLE
Suggested USB socket part number

### ISSUE THREAD

**Issue by richardstephens** [cecio/USBvalve#16]
Hi, I'm looking to build this project for myself. However looking through the USB sockets available on Mouser and Farnell, none of the footprints quite match the PCB.

Do you have part numbers for the USB sockets used in the provided gerbers? Or would you mind providing the EasyEDA file so I can tweak the footprint myself?

**Comment by cecio** [comment]
Hey.

The USB socket is a female USB SMD Type A 90 degrees part, like this one:

https://jlcpcb.com/partdetail/Sofng-USB_302ST/C112455

But you can basically adapt also any other USB type A socket. For example, for some I also used this one

https://www.mouser.it/ProductDetail/SparkFun/PRT-09011?qs=WyAARYrbSnaaObsZj2bzLg%3D%3D

I just had to bend the PINs appropriately before soldering it to the board.

**Comment by richardstephens** [comment]
Thank you! looking forward to building it

**Comment by cecio** [comment]
Thanks to you and for your interest into the project!
