### ISSUE TITLE
Pi Pico Watch Supported Features

### ISSUE THREAD

**Issue by Takiiiiiiii** [cecio/USBvalve#28]
I have a question about USBvalve support for the Pi Pico Watch. I flashed the latest build and verified that it can report actions taken by the PC that it is connected to. I then moved on to test host support and ran into a snag. 

Is the watch supposed to be able to do USB Host for connected USB drives/HID devices from the Type-C port? I assumed that it would as long as you provided it with power from the battery connector, but it does not seem to work like the standard PCB version. 

Cool software regardless.

**Comment by cecio** [comment]
The PI Pico Watch is similar to version 1.1, with single port and so it cannot act as USB Host to detect HID devices. 
Theoretically it can, but you should add an additional port. So basically, for the HID detection you need an additional port.
Thanks for your question and your interest into the project.
