### ISSUE TITLE
writing text files not detected

### ISSUE THREAD

**Issue by gamecioep** [cecio/USBvalve#30]
Hi,
I noticed that when I create a file no popup comes up saying that I am writing. 
But once I save something in this file or I create a folder it does say "writing".
Is this done on purpose?
I am not an expert on this so I don't know how windows deals with new files and if this counts as writing or not.

**Comment by cecio** [comment]
Hey.

Yes, this is expected behavior: if a file with 0 size is created, the writing is not triggered, since you are not modifying any other sector than the one containing the file list. As soon as any data is added to the file, the "writing" message is triggered.
