### ISSUE TITLE
Is there a test scenario?

### ISSUE THREAD

**Issue by CHNO5** [cecio/USBvalve#39]
I just built my first usbvalve and was wondering if there is a test scenario that is available to see the possible issue that can show up on the screen, and to make sure that everything works?

**Comment by NagelTuev** [comment]
To test on the pc, you can simply connect it and, for example, access the readme or delete it, or copy a file to it.

You can test the host usb, e.g. with a keyboard, mouse or usb stick.

Google is your friend when it comes to RubberDuckies, there are relatively simple DIY options

**Comment by cecio** [comment]
Yep, thanks @NagelTuev that was exactly what I would have suggested.
