### ISSUE TITLE
pimoroni pico lipo / trafficlight and small things

### ISSUE THREAD

**Issue by TryBreakFixAgain** [cecio/USBvalve#43]
Hi, 

i had some time and adapted my trafficlight-mod, incl. simplification of the message output, and my modifications for a pimoroni pico lipo, incl. housing STL-files to the 0.18.0 and put them online.

@cecio 
you are welcome to use parts of it.

**Comment by cecio** [comment]
hey thanks a lot @TryBreakFixAgain !

I'll add a section in the README with reference to the project, thanks!
