### ISSUE TITLE
USBvalve not visible from pc

### ISSUE THREAD

**Issue by iali9906** [cecio/USBvalve#47]
my USBValve is not detected by the pc.

here are the steps of what happens:

1) plug the cable into the Pico micro USB
2) then connect the cable to the windows 11 pc.
3) nothing appears on the pc
4) "USBvalve - 0.13.0 - [+] Selftest: OK" appears on the lcd.

i tried to flash new firmware, but by holding down the reset button "[+] RESETTING" appears and stays fixed on the lcd without showing anything on the pc. if i instead click it once the reset word appears and reappears right away, but nothing changes.

Thanks

**Comment by cecio** [comment]
Hey.

Strange issue: I'm not sure if you tried to put the device in BOOTSEL mode. To do it, you have to unplug the USBvalve (Pico), hold down the BOOTSEL button and plug the cable in.
If you did it right, you should see a new device on the PC (named RPI-RP2) and the LCD should remain off.
In this mode you can test if your Pico is working or not.

Other random things to check:
- if the cable is a data cable (some of USB cable are just for power)
- if your PC has any security software or setting blocking the usage of USB devices
