### ISSUE TITLE
Missing parts for USB Pipe

### ISSUE THREAD

**Issue by TheLumpOfDirt** [cecio/USBvalve#50]
I was looking at the BOM for USB Pipe and I noticed that you are missing a listing for resistors R7 and R8.

**Comment by cecio** [comment]
Thanks for the notification, I forward this to @LiPolymer for checking.
Thanks

**Comment by LiPolymer** [comment]
> I was looking at the BOM for USB Pipe and I noticed that you are missing a listing for resistors R7 and R8.

I'm sorry for that.
R7 and R8 aren't actually connected to anything. They are added for circuit debugging purposes
![image](https://github.com/user-attachments/assets/35068123-93b0-4fca-8846-75752198f32d)
![image](https://github.com/user-attachments/assets/04ce9d64-5cd7-429f-9029-4980df26d805)
I'll note this in the README and BOM.
Apologies again :(

**Comment by cecio** [comment]
Fixed with Pull Request #51 
Thanks a lot @LiPolymer  for your fast feedback!

**Comment by LiPolymer** [comment]
That's my duty ;)
