### ISSUE TITLE
.stl file for 3d printed spacer

### ISSUE THREAD

**Issue by edygert** [cecio/USBvalve#7]
Do you have the .stl file for the 3d printed spacer? I don't see it in the repo. I could use tape but the spacer looks so much nicer! Thank you so much for the demo lab at Defcon and for the free unit. I showed it to my son and he took one look at the spacer and said wow, that's nice printing. lol

**Comment by cecio** [comment]
Hey, thanks to you for your feedback!

Here is the link of the spacer: https://www.thingiverse.com/thing:4748043

Let me know if you need something else. :-)

**Comment by edygert** [comment]
Thank you!
